
literkaprzedszkole_url = 'https://www.literkaprzedszkole.pl/'
charakteryplus_url = 'https://www.charakteryplus.pl/'

strony = ['https://praktycznafizjoterapia.pl', 'https://charaktery.eu', 'https://forumginekologii.pl',
          'https://psychologiawpraktyce.pl', 'https://food-forum.pl', 'https://monitorszkoly.pl',
          'https://mieszkanie-i-wspolnota.pl', 'https://forumlogopedy.pl', 'https://glospedagogiczny.pl',
          'https://animal-expert.pl', 'https://wychowaniewprzedszkolu.com.pl', 'https://praktycznastomatologia.pl',
          'https://praktyczna-ortopedia.pl', 'https://bikeboard.pl', 'https://naturoterapiawpraktyce.pl', 'https://forumpediatrii.pl',
          'https://monitorprzedszkola.pl', 'https://doradcawpomocyspolecznej.pl', 'https://naturoterapiawpraktyce.pl', 'https://forumpediatrii.pl',
          'https://monitorprzedszkola.pl', 'https://doradcawpomocyspolecznej.pl', 'https://body-challenge.pl', 'https://monitor-zamowien.pl',
          'https://zycieszkoly.com.pl', 'https://wychowaniefiz.pl', 'https://terapiaspecjalna.pl', 'https://wiadomoscidermatologiczne.pl', 'https://ksiegowego.pl',
          'https://o-m.pl', 'https://hrbusinesspartner.pl', 'https://menedzer-produkcji.pl', 'https://doradcazarzadcy.pl', 'https://nowa-sprzedaz.pl',
          'https://czasopismobiologia.pl', 'https://sm-manager.pl', 'https://realestatemagazine.pl', 'https://sluzby-ur.pl', 'https://czasopismopolonistyka.pl',
          'https://malecharaktery.pl', 'https://magazyn-ecommerce.pl', 'https://mamy-czas.pl', 'https://magazynswiatseniora.pl', 'https://czasopismomatematyka.pl',
          'https://kongres-forumpediatrii.pl', 'https://horyzontyanglistyki.pl', 'https://ksiegowego.pl', 'https://vettrends.pl', 'https://laj.pl', 'https://animalexpertplus.pl',
          'https://kongres-dietoterapia.pl', 'https://kadry-i-place.com.pl', 'https://kongresbehawiorystyczny.pl', 'https://pastoralis.pl', 'https://czasopismokatecheza.pl',
          'https://opieka-farmaceutyczna.eu', 'https://kongres-zaburzeniasi.pl', 'https://pr-manager.pl', 'https://kongres-arteterapia.pl', 'https://mojprzedszkolak.pl',
          'https://pastoralis.pl', 'https://pediatriaplus.pl', 'https://forumpomocyspolecznej.pl', 'https://mspmag.pl', 'https://konferencja-reumatologiczna.pl',
          'https://bikeboard.pl', 'https://miesiecznikfpn.pl', 'https://teczkaterapii.pl', 'https://biznes-hotel.pl', 'https://sur-bootcamp.pl', 'https://czasopismomindfulness.pl',
          'https://barber-magazine.pl', 'https://teczkapsychologa.pl', 'https://regulacjebudowlane.pl', 'https://remmeeting.pl', 'https://doradcaksiegowego.pl',
          'https://dochodowy.com.pl', 'https://mindfully.pl', 'https://magazynroweryelektryczne.pl', 'https://uczen-niepelnosprawny.pl',
          'https://psychopatologiadlapsychologow.pl', 'https://forum-budownictwa.pl', 'https://tcmwpraktyce.pl', 'https://przewodnikporodo.pl',
          'https://konferencja-neurologiczna.pl', 'https://kongresnaturoterapii.pl', 'https://kongresanglistow.pl', 'https://hrbusinessguide.pl',
          'https://kadry-i-place.com.pl', 'https://terapiaprzedszkolaka.pl', 'https://teczkapedagoga.pl', 'https://kongrespolonistyczny.pl',
          'https://kongrespolonistyczny.pl', 'https://kurs-logo.pl', 'https://kongresbhp.pl', 'https://trendywneurologii.pl', 'https://emocjewprzedszkolu.pl',
          'https://zajeciawyrownawcze.pl', 'https://teczkanaturoterapii.pl', 'https://konferencjanowoczesnegohr.pl', 'https://kierownik-budowlany.pl',
          'https://konferencja-logopedyczna.pl', 'https://kongres-wf.pl', 'https://konferencjaneurodydaktyczna.pl', 'https://fizjoterapianajmlodszych.pl',
          'https://doradztwowszkole.pl', 'https://kongreszarzadcy.pl', 'https://ekspertzamowienpublicznych.pl',
          'https://kongresgeograficzny.pl', 'https://diagnostykaplodu.pl', 'https://ksiazka-obiektu.pl', 'https://fizjoterapiazwierzat.com.pl', 'https://kongresniepubliczne.pl',
          'https://kongres-matematykow.pl', 'https://konferencja-cukrzyca.pl', 'https://kongresfizchem.pl', 'https://ocenazgodnoscimaszyn.pl', 'https://kurs-fizjo.pl',
          'https://obrazowaniewortopedii.pl', 'https://hrimpactconference.pl', 'https://szefowie-produkcji.pl', 'https://konferencja-skoradziecka.pl',
          'https://konferencja-onkologiczna.pl', 'https://strategie-ur.pl', 'https://dietywpediatrii.pl', 'https://kongresterapeutow.pl', 'https://fizjoterapia-sport.pl',
          'https://fizjoterapia-covid.pl', 'https://pedodoncja-stepbystep.pl', 'https://kodowaniewprzedszkolu.pl', 'https://konferencja-dietetyczna.pl',
          'https://procedurysanitarne.pl', 'https://kongres-edukacjawczesnoszkolna.pl', 'https://konferencja-stomatologiczna.pl', 'https://konferencja-ux.pl',
          'https://atrakcyjnezajecia.pl', 'https://konferencja-zp.pl', 'https://kongresoswiatowy.pl', 'https://nowoczesnybibliotekarz.pl', 'https://pzp2021.pl',
          'https://endodoncja-kurs.pl', 'https://kongresprofesjonalistowhr.pl', 'https://warsztaty-fizchem.pl', 'https://kongresbiologiczny.pl',
          'https://aboutid.xyz', 'https://best1be.xyz', 'https://whereyougofor.xyz', 'https://konferencjabibliotekarzy.pl',
          'https://flippingbook.ocenazgodnoscimaszyn.pl', 'https://teczkabhp.pl', 'https://flippingbook.ocenazgodnoscimaszyn.pl', 'https://customerservicemagazine.pl',
          'https://kongresmindfulness.pl', 'https://charakteryplus.pl', 'https://konferencjazlobki.pl', 'https://ux-academy.pl', 'https://kongresliderekbiznesu.pl',
          'https://flippingbook.zycieszkoly.com.pl', 'https://flippingbook.forumlogopedy.pl', 'https://cukrzyca-konferencja.pl', 'https://spotkaniaznaturoterapia.pl',
          'https://teczkazarzadcy.pl', 'https://flippingbook.monitorprzedszkola.pl', 'https://kongresochronysrodowiska.pl', 'https://flippingbook.czasopismomatematyka.pl',
          'https://receptury-roslinne.pl', 'https://prenumerata.eventmanagement.pl', 'https://cc.bingj.com', 'https://fotowoltaika-zrodla-energii-webinar.pl' ,'https://cc.bingj.com',
          'https://fotowoltaika-zrodla-energii-webinar.pl', 'https://flippingbook.praktycznastomatologia.pl', 'https://zdrowe-swieta.pl',
          'https://flippingbook.kierownik-budowlany.pl', 'https://www-1animal-2expert-1pl-100117ful08dd.han.up.poznan.pl',
          'https://www-1animal-2expert-1pl-100117ful08dd.han.up.poznan.pl', 'https://www-1animal-2expert-1pl-100117ful08dd.han.up.poznan.pl',
          'https://flippingbook.procedurysanitarne.pl', 'https://ekurs.sigma.org.pl', 'https://nsplus.com.pl', 'https://flippingbook.terapiaprzedszkolaka.pl',
          'https://flippingbook.emocjewprzedszkolu.pl', 'https://flippingbook.atlasrehabilitacji.pl', 'https://flippingbook.regulacjebudowlane.pl',
          'https://flippingbook.wychowaniefiz.pl', 'https://flippingbook.wychowaniefiz.pl', 'https://flippingbook.atrakcyjnezajecia.pl', 'https://flippingbook.doradztwowszkole.pl',
          'https://www.literkaprzedszkole.pl', 'https://www.charakteryplus.pl/', 'https://www.net-fiz.pl/',
          'https://www.pediatriaplus.pl/', 'https://www.animalexpertplus.pl/', 'https://www.doradcaksiegowego.pl/', 'https://www.uniqskills.com/',
          'https://flippingbook.terapiaprzedszkolaka.pl',
          'https://flippingbook.emocjewprzedszkolu.pl', 'https://flippingbook.atlasrehabilitacji.pl', 'https://flippingbook.regulacjebudowlane.pl',
          'https://flippingbook.wychowaniefiz.pl', 'https://flippingbook.wychowaniefiz.pl', 'https://flippingbook.atrakcyjnezajecia.pl', 'https://flippingbook.doradztwowszkole.pl',
          'https://www.literkaprzedszkole.pl', 'https://www.charakteryplus.pl/', 'https://www.net-fiz.pl/',
          'https://www.pediatriaplus.pl/', 'https://www.animalexpertplus.pl/', 'https://www.doradcaksiegowego.pl/', 'https://www.uniqskills.com/', 'https://www.mieszkanie-i-wspolnota.pl/', 'https://animal-expert.pl',
			'https://animalexpertplus.pl',
			'https://atlasrehabilitacji.pl',
			'http://www.atrakcyjnezajecia.pl',
			'https://www.zajeciawyrownawcze.pl',
			'https://diagnostykaplodu.pl',
			'https://www.badaniecheckmate.pl/',
			'https://www.barber-magazine.pl',
			'https://www.barber-magazine.pl/',
			'https://bikeboard.pl/',
			'https://www.jaksprzedacrower.pl',
			'https://czasopismobiologia.pl',
			'https://biznes-hotel.pl',
			'https://restauracje-catering.pl',
			'https://body-challenge.pl',
			'https://charaktery.eu/',
			'https://www.charakteryplus.pl/',
			'https://customerservicemagazine.pl',
			'https://www.czasopismokatecheza.pl/',
			'https://www.dentalcases.pl/',
			'https://www.kurs-weterynaria.pl/',
			'https://www.dietletter.pl',
			'https://www.domowe-przedszkole.eu',
			'https://doradcaksiegowego.pl',
			'https://doradcaprawnynieruchomosci.pl',
			'https://doradcawpomocyspolecznej.pl',
			'https://doradcazarzadcy.pl',
			'https://www.doradztwowszkole.pl',
			'https://dzieckoiruch.pl',
			'https://www.emocjewprzedszkolu.pl',
			'https://endodoncja-kurs.pl/',
			'https://www.event-beauty.pl',
			'https://www.fizjoterapianajmlodszych.pl',
			'https://www.fizjoterapia-covid.pl/',
			'https://www.fizjoterapia-sport.pl',
			'https://fizjoterapiazwierzat.com.pl',
			'https://food-forum.pl',
			'https://forumlogopedy.pl',
			'https://forum-budownictwa.pl',
			'https://forumpediatrii.pl',
			'https://miesiecznikfpn.pl',
			'https://forumginekologii.pl',
			'https://www.forumpomocyspolecznej.pl/',
			'https://praktycznastomatologia.pl',
			'https://www.remmeeting.pl/',
			'https://www.gastroenterologia-forum.pl/',
			'https://glospedagogiczny.pl',
			'https://www.dietywpediatrii.pl',
			'https://horyzontyanglistyki.pl',
			'https://hrbusinessguide.pl',
			'https://hrbusinesspartner.pl',
			'https://www.hrimpactconference.pl/',
			'https://hrplus.pl',
			'https://www.omguide.pl/',
			'https://i-com.pl',
			'https://innowacyjnamatematyka.pl',
			'https://joga-twarzy.pl',
			'https://kardiologia-i-diabetologia.pl',
			'https://www.kodowaniewprzedszkolu.pl/',
			'https://www.konferencjabibliotekarzy.pl/',
			'https://www.konferencja-cukrzyca.pl/',
			'https://www.cukrzyca-konferencja.pl/',
			'https://www.kongresoswiatowy.pl/',
			'https://www.farmacjawpandemii.pl/',
			'https://www.konferencja-neurologiczna.pl/',
			'https://www.hrsummermeeting.pl/',
			'https://www.konferencjainstytucjipomocowych.pl',
			'https://www.konferencjakadrydlabiznesu.pl',
			'https://www.konferencja-makeup.pl/',
			'https://konferencjaneurodydaktyczna.pl/',
			'https://www.konferencjanowoczesnegohr.pl/',
			'https://www.konferencja-odpornosc.pl/',
			'https://www.konferencja-onkologiczna.pl/',
			'http://www.onkologiczna-konferencja.pl/',
			'https://www.konferencjanewstarthr.pl/',
			'https://obrazowaniewortopedii.pl',
			'https://konferencja-poloznych.pl/',
			'https://www.kongresterapeutow.pl/',
			'https://www.konferencja-reumatologiczna.pl',
			'https://www.konferencja-skoradziecka.pl/',
			'https://konferencja-stomatologiczna.pl',
			'https://www.konferencja-ux.pl/',
			'https://www.konferencjavettrends.pl',
			'https://www.konferencja-zp.pl/',
			'https://www.konferencjazlobki.pl',
			'https://www.konferencja-dietetyczna.pl/',
			'https://www.kongresanglistow.pl',
			'https://www.kongres-arteterapia.pl/',
			'https://www.kongresbehawiorystyczny.pl/',
			'https://www.kongrescharaktery.pl/',
			'https://kongresdietetyczny.pl',
			'https://www.kongres-dietoterapia.pl/',
			'https://www.kongres-wf.pl/',
			'https://www.kongresdyrektorowfinansowych.pl/',
			'https://kongres-edukacjimuzycznej.pl',
			'https://www.kongres-edukacjawczesnoszkolna.pl',
			'https://www.kongres-edukacjazfilmem.pl',
			'https://www.kongresfizchem.pl',
			'https://www.kongres-forumpediatrii.pl/',
			'https://kongresgeograficzny.pl',
			'https://www.kongresgermanistow.pl/',
			'https://www.kongres-kgw.pl',
			'https://www.kongresgp.pl',
			'https://www.kongresjezykowy.pl/',
			'https://kongresliderekbiznesu.pl',
			'https://warsztatyrodzicielskie.pl',
			'https://www.kongres-matematykow.pl',
			'https://www.kongresniepubliczne.pl/',
			'https://www.kongresochronysrodowiska.pl',
			'https://www.kongres-online.pl',
			'https://www.konferencjaeduonline.pl/',
			'https://kongrespolonistyczny.pl',
			'https://www.kongresprofesjonalistowhr.pl',
			'https://kongresprzyrodniczy.pl',
			'https://www.kongrespsychologiczny.pl/',
			'https://szefowie-produkcji.pl/',
			'https://www.kongrestelemedycyna.pl/',
			'https://www.kongresterapiaspecjalna.pl',
			'https://www.kongres-zaburzeniasi.pl/',
			'https://www.kongreszarzadcy.pl',
			'https://www.ksiazka-obiektu.pl',
			'https://www.kurs-endokrynologia.pl/',
			'https://kurs-fizjo.pl',
			'https://www.leczenieczerniaka.pl/',
			'https://www.leczeniercc.pl/',
			'https://www.szkolacharaktery.pl/',
			'https://www.instrukcjeksiegowe.pl/',
			'https://www.literka.pl/',
			'https://www.laj.pl',
			'https://magazyn-ecommerce.pl',
			'https://o-m.pl/',
			'https://www.malecharaktery.pl/',
			'https://www.maly-uczen.pl',
			'https://mamy-czas.pl/',
			'https://czasopismomatematyka.pl',
			'https://www.kursterapeutasi.pl/',
			'https://menedzer-produkcji.pl',
			'https://mieszkanie-i-wspolnota.pl',
			'https://mindfully.pl',
			'https://modern-warehouse.pl',
			'https://mojprzedszkolak.pl',
			'https://monitorprzedszkola.pl',
			'https://monitorszkoly.pl',
			'https://monitor-zamowien.pl',
			'https://mspmag.pl',
			'https://kurs-metodyterapii.pl',
			'https://www.spotkaniaznaturoterapia.pl/',
			'https://www.kongresnaturoterapii.pl',
			'https://naturoterapiawpraktyce.pl',
			'https://net-fiz.pl',
			'https://nowa-sprzedaz.pl',
			'https://www.nsplus.pl/',
			'https://regulacjebudowlane.pl',
			'https://Nowe prawo budowlane i przepisy wykonawcze',
			'https://www.noweprawoodpadowe.pl',
			'https://www.ekspertzamowienpublicznych.pl',
			'https://przewodnikporodo.pl',
			'https://nowoczesnybibliotekarz.pl',
			'https://nm.pl',
			'https://nowy.e-firma.pl',
			'https://www.kongresmindfulness.pl/',
			'https://www.kongresbhp.pl/',
			'https://ksiazka-obiektu.pl',
			'https://opieka-farmaceutyczna.eu',
			'https://www.opiekaokoloporodowa.pl/',
			'https://ortopediainterdyscyplinarnie.pl',
			'https://pakietbiznesowy.pl',
			'https://www.poradnikpediatria.pl/',
			'https://pediatriaplus.pl/',
			'https://pedodoncja-stepbystep.pl',
			'https://www.physiosummit.pl/',
			'https://literkaprzedszkole.pl',
			'https://www.audiobook.charaktery.eu',
			'https://czasopismopolonistyka.pl',
			'https://polskilad2022.pl',
			'https://www.kierownik-budowlany.pl',
			'https://poradnik-ebiznesu.pl',
			'https://postepowaniezbolem.pl',
			'https://pr-manager.pl',
			'https://praktycznafizjoterapia.pl',
			'https://praktyczna-ortopedia.pl',
			'https://www.prenumerata.charaktery.eu/',
			'https://www.protetyka-kurs.pl/',
			'https://psychiatriadlapsychologow.pl',
			'https://psychologiawpraktyce.pl',
			'https://psychopatologiadlapsychologow.pl',
			'https://pytaniadoeksperta.pl/',
			'https://www.pzp2021.pl',
			'https://www.raknerkiesmo.pl',
			'https://realestatemagazine.pl',
			'https://receptury-roslinne.pl',
			'https://remcongress.pl',
			'https://rentownyhotel.pl',
			'https://restaurant-academy.pl',
			'https://www.rodzinawkryzysie.pl/',
			'https://magazynroweryelektryczne.pl',
			'https://www.szkolenie-prawopracy.pl',
			'https://sluzby-ur.pl',
			'https://sm-manager.pl',
			'https://www.dochodowy.com.pl/',
			'https://kadry-i-place.com.pl/',
			'https://ksiegowego.pl',
			'https://www.stom-online.pl/',
			'https://www.strategie-ur.pl/',
			'https://www.subskrypcja.dietcase.pl/',
			'https://www.suplementydietywchzs.pl/',
			'https://www.supply-chain.pl/',
			'https://www.sur-bootcamp.pl/',
			'https://www.magazynswiatseniora.pl',
			'https://opiekun-zlobek.pl/',
			'https://usg-gin.pl/',
			'https://www.tcmwpraktyce.pl/',
			'https://teczkadietetyka.pl/',
			'https://teczkanaturoterapii.pl/',
			'https://teczkapedagoga.pl',
			'https://www.teczkapracykatechety.pl/',
			'https://www.teczkalogopedy.pl',
			'https://teczkapsychologa.pl',
			'https://www.nowe-procedury-budowlane.pl',
			'https://www.teczkaterapii.pl',
			'https://www.teczka-wychowawcy.pl',
			'https://www.procedurysanitarne.pl',
			'https://www.teczkazarzadcy.pl',
			'https://kurs-logo.pl',
			'https://terapiaprzedszkolaka.pl',
			'https://terapiaspecjalna.pl',
			'https://termomodernizacja.info',
			'https://teczkabhp.pl',
			'https://trendywneurologii.pl',
			'https://uczen-niepelnosprawny.pl',
			'https://ocenazgodnoscimaszyn.pl',
			'http://www.ux-academy.pl/',
			'http://ux-ecommerce.pl/',
			'https://ux-trends.pl',
			'https://www.kongresbiologiczny.pl/',
			'https://vettrends.pl',
			'https://www.dietexpert-workshop.pl/',
			'https://www.warsztatydlabibliotekarzy.pl/',
			'https://warsztaty-fizchem.pl/',
			'https://www.warsztatyliderekbiznesu.pl',
			'https://www.warsztatyliderowhr.pl/',
			'https://warsztaty-stomatologiczne.pl/',
			'https://warsztaty-wf.pl/',
			'https://warsztaty.nm.pl',
			'https://webfleetexperts.pl',
			'https://www.webinar-magazyn.pl/',
			'https://webinar.placowki-niepubliczne.pl/',
			'https://webinar.pracowniasi.pl',
			'https://webinares.pl',
			'https://webinarmes.pl',
			'https://wiadomoscidermatologiczne.pl',
			'https://www.superanimalexpert.pl',
			'https://wychowaniefiz.pl',
			'https://wychowaniewprzedszkolu.com.pl',
			'https://www.konferencja-logopedyczna.pl',
			'https://zaufanyterapeuta.charaktery.eu',
			'https://zdrowe-swieta.pl',
			'https://zelazopoloznictwoginekologia.pl',
			'https://zycieszkoly.com.pl',
		  	'https://www.nadzor-pedagogiczny.pl/',
		  	'https://www.pedagogia.pl/',
		  'https://www.pracowniasi.pl/',
		  'http://www.zapobiecprzemocy.pl/',
		  'http://www.profilaktykauzaleznien.pl/',
		  'https://www.administracjawoswiacie.pl/',
		  'http://www.ewaluacjawszkole.pl/',
		  'https://akademiastomatologa.pl/'
		  ]


"""
wywalone
 'https://warsztaty-wf.pl',



"""